ch = 'A'
print("字符:%c" % ch)

s = 'Python'
print("字符串：%s" % s)
i = 1024
print("十进制(decimal)整数:%d" % i)
print("指定宽度为6:%6d" % i)
print("带符号的十进制整数:%i" % i)
print("无符号的十进制整数:%u" % i)
print("十进制浮点数:%f" % i)
print("指定精度(保留两位小数):%.2f" % i)
print("指定宽度和精度:%5.2f" % i)
print("科学计数:%e" % i)
print("科学计数2:%E" % i)
print("八进制:%o" % i)
print("十六进制:%X" % i)
print("十六进制2:%x" % i)
print("八进制，添加前导符号:%#o" % i)
print("十六进制，添加前导符号:%#X" % i)
print("十六进制，添加前导符号2:%#x" % i)
print("左对齐:%-10d" % i)
print("右对齐:%+10d" % i)
print("空位补0:%010d" % i)
